In [6]:
import torch
import numpy as np
a = np.array([[0.1, 0.2], 
              [0.05, 0.4]])
outputs = torch.tensor(a)
print(a)
print(outputs.argmax(1)) # --->
print(outputs.argmax(0))
preds = outputs.argmax(1)
targets = torch.tensor([0, 1])
print(preds == targets)
print((preds == targets).sum())

[[0.1  0.2 ]
 [0.05 0.4 ]]
tensor([1, 1])
tensor([0, 1])
tensor([False,  True])
tensor(1)


In [8]:
!nvidia-smi

Sun Aug  6 23:10:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.01       Driver Version: 516.01       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    14W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------