# Ndarray 对象

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
# 多于一个维度
a = np.array([[1, 2], [3, 4]])
print(a)
# ndmin
b = np.array([1, 2, 3, 4], ndmin=2)
print(b)
# dtype
c = np.array([1,2,3,4], dtype=complex)
print(c)

[[1 2]
 [3 4]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# 数据类型

In [3]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)

int32


In [4]:
# i1 i2 i4 i8
# int8 int16 int32 int64
dt = np.dtype('i4')
print(dt)

int32


In [7]:
# 创建结构化数据类型
dt = np.dtype([('age', np.int8)])
print(dt)
# 将数据类型应用于ndarray对象
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a)
# 类型字段名可以用于存取实际的age列
print(a['age'])

[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]


In [11]:
# 结构化数据类型student
import numpy as np
student = np.dtype([('name','U20'), ('age', 'i1'), ('marks', 'f4')])
print(student)
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)
print(a['name'])

[('name', '<U20'), ('age', 'i1'), ('marks', '<f4')]
[('abc', 21, 50.) ('xyz', 18, 75.)]
['abc' 'xyz']
