# 迭代数组

In [2]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a):
    print(x, end=", ")

[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

In [3]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a.T):
    print(x, end=", ")
print('\n')
for x in np.nditer(a.T.copy(order='C')):
    print(x, end=", ")

[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 

In [6]:
# 控制遍历顺序
a = np.arange(0,60, 5)
a = a.reshape(3,4)
b = a.copy(order='C')
c = a.copy(order='F')
for x in np.nditer(b):
    print(x, end=",")
print("")
for x in np.nditer(c):
    print(x, end=",")
print("")
for x in np.nditer(a, order='C'):
    print(x,end=",")

0,5,10,15,20,25,30,35,40,45,50,55,
0,20,40,5,25,45,10,30,50,15,35,55,
0,5,10,15,20,25,30,35,40,45,50,55,

In [13]:
# 修改数组中元素的值
a = np.arange(0, 60, 5).reshape(3,4)
print(a)
for x in np.nditer(a, op_flags=['readwrite']):
    # x[:] = x*2
    x[...] = x*2 # x[...]会将迭代过程中的值赋值给原始数组中对应位置的元素，从而实现直接修改原始数组的效果。
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


# Numpy数组操作

In [14]:
import numpy as np

a = np.arange(9).reshape(3,3)
for row in a:
    print(row)

# 数组元素迭代器
for element in a.flat:
    print(element)

[0 1 2]
[3 4 5]
[6 7 8]
0
1
2
3
4
5
6
7
8


In [16]:
# 拷贝
a = np.arange(8).reshape(2,4)
print(a)
print(a.flatten())
print(a.flatten(order='F'))

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


In [17]:
# np.ravel()
# view
a = np.arange(8).reshape(2,4)
b = a.ravel()
print(a)
print(b)
b[0] = -1
print(a)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[[-1  1  2  3]
 [ 4  5  6  7]]


In [26]:
a = np.arange(8).reshape(2,2,2)
print(a)
# print(np.where(a==6)) # 获取索引
idx = np.where(a==6)
print(idx)
print(a[idx])
print(a[idx[0],idx[1],idx[2]])
print(np.squeeze(a[idx]))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(array([1], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))
[6]
[6]
6


In [29]:
# 翻转数组
# numpy.rollaxis
print(a)
print(np.where(a==5))
b = np.rollaxis(a,2,0) # 将轴2移动到轴0
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [30]:
# np.swapaxes
a = np.arange(8).reshape(2,2,2)
print(a)
print(np.swapaxes(a,2,0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [39]:
# 广播
import numpy as np
x = np.array([[1], [2], [3]])
y = np.array([4, 10, 18])
print(f'X shape {x.shape}, Y shape {y.shape}')

b = np.broadcast(x, y) # 对y广播x
# type(b)

r,c = b.iters
print(next(r), next(c))
print(next(r), next(c))

print(f'{b.shape=}')
print(b)

b = np.broadcast(x, y)
c = np.empty(b.shape)
print(c.shape)
c.flat = [u + v for (u,v) in b]

print(c)

print(x+ y)

X shape (3, 1), Y shape (3,)
1 4
1 10
b.shape=(3, 3)
(3, 3)
[[ 5. 11. 19.]
 [ 6. 12. 20.]
 [ 7. 13. 21.]]
[[ 5 11 19]
 [ 6 12 20]
 [ 7 13 21]]


In [47]:
# 广播
a = np.arange(12).reshape(2,2,3)
b = np.arange(6).reshape(2,3)
print(a+b)

[[[ 0  2  4]
  [ 6  8 10]]

 [[ 6  8 10]
  [12 14 16]]]


In [48]:
# np.broadcast_to
a = np.arange(4).reshape(1,4)
print(f'{a = }')

print(np.broadcast_to(a, (4,4)))

a = array([[0, 1, 2, 3]])
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [51]:
# np.expand_dims
x = np.array(([1, 2], [3, 4]))
print(f'{x = }')
y = np.expand_dims(x, axis=0)
print(f'{y = }')
print(f'{x.shape = }, {y.shape = }')
print(f'{x.ndim = }, {y.ndim = }')

x = array([[1, 2],
       [3, 4]])
y = array([[[1, 2],
        [3, 4]]])
x.shape = (2, 2), y.shape = (1, 2, 2)
x.ndim = 2, y.ndim = 3


In [54]:
# numpy.squeeze
# 删除数组形状中一维的条目
x = np.arange(9).reshape(1,3,3)
print(x)
y = np.squeeze(x)
print(y)
# y = np.squeeze(x, axis=1)
# print(y)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
# 连接数组
# concatenate
a = np.array([[[1,2],[3,4]]])
b = np.array([[[5,6],[7,8]]])
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [60]:
# np.stack
# 用于沿新轴连接数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.stack((a,b),0))
print(np.stack((a,b),1))
print(np.stack((a,b),2))
print(np.stack((a,b),0).shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [61]:
# np.hstack
# 水平堆叠生成数组
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [62]:
# np.vstack
# 垂直堆叠来生成数组
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [65]:
# 分割数组
# split
# 默认水平切割
a = np.arange(9)
b = np.split(a,3) # 平均分成3个大小相等的数组
print(b)

print(np.split(a,(4,7)))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [68]:
a = np.arange(16).reshape(4,4)
print(a)
b = np.split(a, 2)
print(b)

b = np.split(a,2,axis=1)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [71]:
# hsplit
import numpy as np
a = np.arange(12).reshape(2,6)
print(a)

print(np.hsplit(a, 3))
print(np.vsplit(a, 2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]


In [73]:
# 元素的添加与删除
# append
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.append(a, [7,8,9]))
print(np.append(a, [[7,8,9]], axis=0))
print(np.append(a, [[5,5,5],[7,8,9]], axis=1))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [76]:
# insert
# axis 如未提供则输入数组会被展开
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.insert(a, 3, [11,12]))
# 广播数组
print(np.insert(a, 1,[11], axis=0))
print(np.insert(a,1,11,axis=1))

[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [80]:
# delete
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,5))
print(np.delete(a, 1, axis=1)) # 删除第二列
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.delete(a, np.s_[::2]))
print(np.delete(a, a[::2]))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[ 2  4  6  8 10]
[1 3 5 7 9]


In [82]:
# numpy.unique
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)
u = np.unique(a)
print(u)

u, indices = np.unique(a, return_index=True)
print(indices)

u, indices = np.unique(a, return_inverse=True)
print(indices)

[5 2 6 2 7 5 6 8 2 9]
[2 5 6 7 8 9]
[1 0 2 4 7 9]
[1 0 2 0 3 1 2 4 0 5]


# 位运算

In [3]:
import numpy as np
a, b = 13, 17
print(f'{bin(a) = }, {bin(b) = }')
print(np.bitwise_and(13,17))
print(np.bitwise_or(a, b))

bin(a) = '0b1101', bin(b) = '0b10001'
1
29


In [5]:
# invert
print(np.invert(np.array([13], dtype=np.uint8)))
print(bin(13))
print(bin(242))

[242]
0b1101
0b11110010


In [8]:
print(np.binary_repr(13, width=8))
print(np.left_shift(10,2))
print(10<<2)

00001101
40
40
