# 迭代数组

In [2]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a):
    print(x, end=", ")

[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

In [3]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a.T):
    print(x, end=", ")
print('\n')
for x in np.nditer(a.T.copy(order='C')):
    print(x, end=", ")

[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 

In [6]:
# 控制遍历顺序
a = np.arange(0,60, 5)
a = a.reshape(3,4)
b = a.copy(order='C')
c = a.copy(order='F')
for x in np.nditer(b):
    print(x, end=",")
print("")
for x in np.nditer(c):
    print(x, end=",")
print("")
for x in np.nditer(a, order='C'):
    print(x,end=",")

0,5,10,15,20,25,30,35,40,45,50,55,
0,20,40,5,25,45,10,30,50,15,35,55,
0,5,10,15,20,25,30,35,40,45,50,55,

In [13]:
# 修改数组中元素的值
a = np.arange(0, 60, 5).reshape(3,4)
print(a)
for x in np.nditer(a, op_flags=['readwrite']):
    # x[:] = x*2
    x[...] = x*2 # x[...]会将迭代过程中的值赋值给原始数组中对应位置的元素，从而实现直接修改原始数组的效果。
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


# Numpy数组操作