# numpy数组属性

In [4]:
import numpy as np
a = np.arange(24)
print(a)
print(a.ndim)
b = a.reshape(2, 4, 3)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
3


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


# Numpy创建数组

In [9]:
# np.empty
import numpy as np
x = np.empty([3, 2], dtype = int)
print(x)

[[-744136672        497]
 [         0          0]
 [         1          0]]


In [17]:
# np.zeros
x = np.zeros(5)
y = np.zeros((5,), dtype=int)
print(x)
print(y)
z = np.zeros([3,2], dtype = [('x', 'i4'), ('y', 'f8')])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]


In [19]:
# np.zeros_like 
a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
print(b)

[[0 0 0]
 [0 0 0]]


# 从已有的数组创建ndarray

In [20]:
# asarray
import numpy as np
x = [(1,2,3),(1,2)]
a = np.array(x)
b = np.asarray(x)
print(a)
print(b)

[(1, 2, 3) (1, 2)]
[(1, 2, 3) (1, 2)]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_13044\973029324.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array(x)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13044\973029324.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.asarray(x)


In [24]:
x = [1.0,2,3]
a = np.asarray(x, dtype=np.int32)
print(a)

[1 2 3]


In [29]:
# np.frombuffer
s = "Hello World"
a = np.frombuffer(s.encode("ascii"), dtype="S1")
print(a)
s = "Hello World"
# b = np.frombuffer(s.encode("ascii"), dtype="U1") # 报错 原因：ascii编码并不是一个字节
# print(b)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


# 从数值范围创建数组

In [33]:
# np.arange
import numpy as np
x = np.arange(5)
print(x)
x = np.arange(10,20,2)
print(x)
x = np.arange(10,21,2)
print(x)

[0 1 2 3 4]
[10 12 14 16 18]
[10 12 14 16 18 20]


In [34]:
# np.linspace
import numpy as np
a = np.linspace(10, 20, 5, endpoint=False)
b = np.linspace(10, 20, 5)
print(a)
print(b)

[10. 12. 14. 16. 18.]
[10.  12.5 15.  17.5 20. ]


In [36]:
a = np.linspace(10, 20, 5, endpoint=False, retstep=True)
print(a)
b = np.linspace(1,10,10).reshape((2,5))
print(b)

print(a[0])
print(a[1])

(array([10., 12., 14., 16., 18.]), 2.0)
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[10. 12. 14. 16. 18.]
2.0


In [39]:
# np.logspace
a= np.logspace(1, 2, num=10) # 底数默认为10
print(a)
b = np.logspace(0, 9, num=10, base=2)
print(b)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
