# 字符串函数

In [1]:
# add
import numpy as np
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))

['helloabc' 'hixyz']


In [2]:
# multiply
print(np.char.multiply('Runoob ', 3))

RunoobRunoobRunoob


In [3]:
# center
print(np.char.center('Runoob', 20, fillchar='*'))

*******Runoob*******


In [4]:
# capitalize
print(np.char.capitalize('runoob'))

Runoob


In [5]:
# title
print(np.char.title('i like runoob'))

I Like Runoob


In [6]:
print(np.char.lower(['Runoob','Google']))
print(np.char.upper('Runoob'))

['runoob' 'google']
RUNOOB


In [8]:
print(np.char.split("i like runoob?"))
print(np.char.split('www.runoob.com',sep='.'))
print(np.char.splitlines("i\nlike runoob"))

['i', 'like', 'runoob?']
['www', 'runoob', 'com']
['i', 'like runoob']


In [9]:
# strip 用于移除开头或结尾处的特定字符
print(np.char.strip('ashok arunooba','a'))
print(np.char.strip(['arunooba','admin','java'], 'a'))

shok arunoob
['runoob' 'dmin' 'jav']


In [11]:
# join
print(np.char.join(':', 'runoob'))
print(np.char.join([':','-'],['runoob','google']))

r:u:n:o:o:b
['r:u:n:o:o:b' 'g-o-o-g-l-e']


In [12]:
# replace
print(np.char.replace('i like runoob','oo','cc'))

i like runccb


# 数学函数

In [14]:
import numpy as np

a = np.array([0, 30, 45, 60, 90])
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [15]:
import numpy as np
a = np.array([0, 30, 45, 60, 90])
sin = np.sin(a*np.pi/180)
print(sin)
inv = np.arcsin(sin)
print(inv)
print(f'角度制{np.degrees(inv)}')

[0.         0.5        0.70710678 0.8660254  1.        ]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
角度制[ 0. 30. 45. 60. 90.]


In [19]:
# 舍入函数
# 四舍五入
a = np.array([1.0, 5.55, 123, 0.567, 25.532,-1.11, -1.56])
print(np.around(a))
print(np.around(a, decimals=1))
print(np.around(a, decimals=-1))
print(f'向下取整{np.floor(a)}')
print(f'向上取整{np.ceil(a)}')

[  1.   6. 123.   1.  26.  -1.  -2.]
[  1.    5.6 123.    0.6  25.5  -1.1  -1.6]
[  0.  10. 120.   0.  30.  -0.  -0.]
向下取整[  1.   5. 123.   0.  25.  -2.  -2.]
向上取整[  1.   6. 123.   1.  26.  -1.  -1.]


# 算术函数


In [23]:
# 加减乘乘
a = np.arange(9, dtype=np.float64).reshape(3,3)
b = np.array([10, 10, 10])
print(a)

print(a+b)
print(a*b)
print(a/b)
print(a//b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# 倒数
a = np.array([0.25, 1.33, 1, 100])
print(np.reciprocal(a))

[4.        0.7518797 1.        0.01     ]


# 统计函数

In [27]:
a = np.array([[3,7,5], [8, 4, 3], [2, 4, 9]])
print(a)
print(np.amin(a, 0))
print(np.amin(a, 1))
print(np.amin(a))
print(np.amax(a, 0))
print(np.amax(a, 1))
print(np.amax(a))
# ptp 最大值-最小值
print(np.ptp(a))
print(np.ptp(a,axis=0))
print(np.ptp(a, axis=1))


[[3 7 5]
 [8 4 3]
 [2 4 9]]
[2 4 3]
[3 3 2]
2
[8 7 9]
[7 8 9]
9
7
[6 3 6]
[4 5 7]


In [29]:
# 百分位数
a = np.array([[10, 7, 4], [3, 2, 1]])
print(a)

print(np.percentile(a, 50)) # 50%分位数
print(np.percentile(a,50,axis=0))
print(np.percentile(a,50,axis=1))

[[10  7  4]
 [ 3  2  1]]
3.5
[6.5 4.5 2.5]
[7. 2.]


In [30]:
# average 
# 权重
a = np.array([1, 2, 3, 4])
print(np.average(a))
wts = np.array([4, 3, 2, 1])
print(np.average(a, weights=wts))

2.5
2.0


In [32]:
# 标准差 方差
print(np.std([1,2,3,4]))
print(np.var([1,2,3,4]))

1.118033988749895
1.25


# 排序 条件筛选函数

In [34]:
a = np.array([[3,7],[9,1]])
print(a)
print(np.sort(a))
print(np.sort(a,axis=1))

[[3 7]
 [9 1]]
[[3 7]
 [1 9]]
[[3 7]
 [1 9]]


In [37]:
# sort中排序字段
dt = np.dtype([('name', 'S10'),('age', int)])
a = np.array([("raju",21),("anil",25),("ravi",17),("amar",27)],dtype=dt)
print(a)
print(np.sort(a,order='name'))
print(np.sort(a,order='age'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]
[(b'ravi', 17) (b'raju', 21) (b'anil', 25) (b'amar', 27)]


In [38]:
# argsort索引值
x = np.array([3,1,2,4,0])
print(x)
y = np.argsort(x)
print(y)
print(x[y])

[3 1 2 4 0]
[4 1 2 0 3]
[0 1 2 3 4]


In [40]:
# lexsort
# 多个序列排序
nm = ['raju','anil','ravi','amar']
dv = ('f.y.','s.y.','s.y.','f.y.')
ind = np.lexsort((dv,nm))
print(ind)
print(f'使用索引后来获取排序后的数据{[nm[i] + "," + dv[i] for i in ind]}')

[3 1 0 2]
使用索引后来获取排序后的数据['amar,f.y.', 'anil,s.y.', 'raju,f.y.', 'ravi,s.y.']


In [42]:
# 指定元素的索引
x = np.arange(9.).reshape(3,3)
print(x)
y = np.where(x>3)
print(x[y])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[4. 5. 6. 7. 8.]


In [43]:
# 抽取元素
x = np.arange(9).reshape(3,3)
con = np.mod(x,2) == 0
print(np.extract(con,x))

[0 2 4 6 8]
