# 切片和索引

In [3]:
import numpy as np
a = np.arange(10)
s = slice(2,8,2) # 从索引2开始到索引7停止， 间隔为2
print(a[s])
print(a[2:8:2])


[2 4 6]
[2 4 6]


In [4]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [21]:
# 使用... 
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6],[7, 8, 9]])
print(a[..., 1])
print(a[1,...])
print(a[...,1:])
print(a[:,1:])

[2 4 5 8]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]
 [8 9]]
[[2 3]
 [4 5]
 [5 6]
 [8 9]]


In [ ]:
a = np.arange(12).reshape((3, 4))
print(a)

# 高级索引

In [8]:
# 整数数组索引
import numpy as np
x = np.array([[1,2], [3,4],[5,6]])
y = x[[0, 1, 2], [0,1,0]]
print(y)

[1 4 5]


In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3,1]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

[5 8]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [12]:
# bool索引
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[a>5])

[6 7 8 9]


In [18]:
# ~取补运算来过滤NaN 和 复数
a = np.array((np.nan, 1, 2, np.nan, 3, 4, 5))
print(a[~np.isnan(a)])

a = np.array([1, 2+6j, 5, 3.5 + 5j])
print(a[np.iscomplex(a)])

[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]


In [25]:
# 花式索引
# 二维数组
x = np.arange(32).reshape((8,4))
print(x)
print(x[[4,2,1,7]]) # 读4,2,1,7对应的行
print(x[[4,2,1,7],:])
print(x[[4,2,1,7],...])
print(np.array_equal(x[[4,2,1,7]], x[[4,2,1,7],...]))
print(x[:,[3,1]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
True
[[ 3  1]
 [ 7  5]
 [11  9]
 [15 13]
 [19 17]
 [23 21]
 [27 25]
 [31 29]]


In [28]:
# 笛卡尔积
import numpy as np
x = np.arange(32).reshape((8,4))
print(x)
print(x[np.ix_([1,5,7,2],[0,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6]
 [20 21 22]
 [28 29 30]
 [ 8  9 10]]


# 广播

In [29]:
# a.shape = b.shape
a =np.array([1, 2, 3,4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [30]:
# 形状不同
a = np.array([[0,0,0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [31]:
a = np.array([[0,0,0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
bb = np.tile(b, (4,1))
print(a + bb)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [39]:
a = np.arange(12)
b = a.reshape(3,2,2)
c = np.array([[[1,2]]])
print(b)
print(c)
print('--------')
print(b+c)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[1 2]]]
--------
[[[ 1  3]
  [ 3  5]]

 [[ 5  7]
  [ 7  9]]

 [[ 9 11]
  [11 13]]]
